# ntd configuration
terraform_path = "/home/conlan/Documents/homelab-repos/homelab/terraform"
nixos_path = "/home/conlan/Documents/homelab-repos/homelab/nix-flakes/services"
ssh_user = "root"
ssh_key = "/home/conlan/.ssh/id_ed25519"

[[hosts]]
name = "tailscale"
terraform_resource = "tailscale"
terraform_ip_output = "hosts.tailscale.ip"
nixos_configuration = "tailscale"

[[hosts]]
name = "ns1"
terraform_resource = "ns1"
terraform_ip_output = "hosts.ns1.ip"
nixos_configuration = "ns1"

#[[hosts]]
#name = "nix-ct-test-03"
#terraform_resource = "nix-ct-test-03"
#terraform_ip_output = "hosts.nix-ct-test-03.ip"
#nixos_configuration = "nix-ct-test-03"
