# ntd configuration
terraform_path = "/home/conlan/Documents/homelab-repos/homelab/terraform"
nixos_path = "/home/conlan/Documents/homelab-repos/homelab/nix-flakes/services"
ssh_user = "root"
ssh_key = "/home/conlan/.ssh/id_ed25519"

[[hosts]]
name = "tailscale"
terraform_resource = "tailscale"
terraform_ip_output = "hosts.tailscale.ips"
nixos_configuration = "tailscale"

[[hosts]]
name = "ns1"
terraform_resource = "ns1"
terraform_ip_output = "hosts.ns1.ips"
nixos_configuration = "ns1"

[[hosts]]
name = "ns2"
terraform_resource = "ns2"
terraform_ip_output = "hosts.ns2.ips"
nixos_configuration = "ns2"

[[hosts]]
name = "karakeep"
terraform_resource = "karakeep"
terraform_ip_output = "hosts.karakeep.ips"
nixos_configuration = "karakeep"

[[hosts]]
name = "miniflux"
terraform_resource = "miniflux"
terraform_ip_output = "hosts.miniflux.ips"
nixos_configuration = "miniflux"
